// A curated set of emojis for category icons — the kinds of things personal
// finance categories actually are (dining, home, transport, kids, money, …),
// not the full Unicode set. Each has lowercase `keywords` so the picker's search
// can match by meaning ("car" → 🚗), not just the glyph. Deliberately in-app:
// no dependency, instant, offline. Add freely; keep keywords space-separated.
export type CategoryEmoji = { char: string; keywords: string };

export const CATEGORY_EMOJIS: CategoryEmoji[] = [
  // Dining & drinks
  { char: "🍔", keywords: "food dining burger fast restaurant eat" },
  { char: "🍕", keywords: "food pizza dining takeout" },
  { char: "🌮", keywords: "food taco mexican dining" },
  { char: "🍣", keywords: "food sushi dining restaurant" },
  { char: "🍜", keywords: "food noodles ramen dining" },
  { char: "🍝", keywords: "food pasta dining" },
  { char: "🥡", keywords: "food takeout delivery dining" },
  { char: "☕", keywords: "coffee cafe drink tea" },
  { char: "🍺", keywords: "beer bar alcohol drinks" },
  { char: "🍷", keywords: "wine bar alcohol drinks" },
  { char: "🍦", keywords: "icecream dessert treat" },
  { char: "🍩", keywords: "donut dessert bakery treat" },
  { char: "🍰", keywords: "cake dessert bakery" },
  // Groceries
  { char: "🛒", keywords: "groceries shopping cart supermarket" },
  { char: "🥦", keywords: "groceries vegetables produce food" },
  { char: "🍎", keywords: "groceries fruit produce food" },
  { char: "🥚", keywords: "groceries eggs food" },
  { char: "🥩", keywords: "groceries meat food butcher" },
  { char: "🥖", keywords: "groceries bread bakery food" },
  // Home & utilities
  { char: "🏠", keywords: "home house rent mortgage housing" },
  { char: "🛋️", keywords: "home furniture decor living" },
  { char: "🛏️", keywords: "home bedroom furniture" },
  { char: "🔧", keywords: "home repair maintenance tools fix" },
  { char: "🧹", keywords: "home cleaning chores" },
  { char: "🪴", keywords: "home plants garden decor" },
  { char: "🛁", keywords: "home bath bathroom" },
  { char: "💡", keywords: "utilities electric light power energy" },
  { char: "⚡", keywords: "utilities electric power energy" },
  { char: "💧", keywords: "utilities water bill" },
  { char: "🔥", keywords: "utilities gas heat energy" },
  { char: "🌡️", keywords: "utilities heating cooling hvac climate" },
  { char: "📶", keywords: "utilities internet wifi phone cell" },
  { char: "📱", keywords: "phone mobile cell wireless tech" },
  { char: "💻", keywords: "tech computer laptop software work" },
  { char: "🖥️", keywords: "tech computer desktop work" },
  // Transport
  { char: "🚗", keywords: "car auto transport vehicle drive" },
  { char: "⛽", keywords: "gas fuel car transport gasoline" },
  { char: "🅿️", keywords: "parking car transport" },
  { char: "🚌", keywords: "bus transit transport public" },
  { char: "🚆", keywords: "train transit transport rail commute" },
  { char: "🚲", keywords: "bike bicycle transport cycling" },
  { char: "🛴", keywords: "scooter transport ride" },
  { char: "🚕", keywords: "taxi rideshare uber lyft transport" },
  // Travel
  { char: "✈️", keywords: "travel flight plane airfare trip vacation" },
  { char: "🏨", keywords: "travel hotel lodging trip vacation" },
  { char: "🧳", keywords: "travel luggage trip vacation" },
  { char: "🗺️", keywords: "travel map trip vacation" },
  { char: "🏖️", keywords: "travel beach vacation trip" },
  { char: "⛺", keywords: "travel camping outdoors trip" },
  // Kids, family, school
  { char: "🧸", keywords: "kids children toys baby family" },
  { char: "👶", keywords: "baby kids children family" },
  { char: "🎓", keywords: "education school college tuition graduation" },
  { char: "🏫", keywords: "school education kids tuition" },
  { char: "🎒", keywords: "school kids supplies education" },
  { char: "🖍️", keywords: "kids crafts school supplies art" },
  // Sports & fitness
  { char: "🏀", keywords: "sports basketball kids activity" },
  { char: "⚽", keywords: "sports soccer kids activity football" },
  { char: "🏈", keywords: "sports football activity" },
  { char: "⚾", keywords: "sports baseball kids activity" },
  { char: "🎾", keywords: "sports tennis activity" },
  { char: "🏊", keywords: "sports swimming activity fitness" },
  { char: "🏋️", keywords: "gym fitness workout exercise health" },
  { char: "🧘", keywords: "yoga fitness wellness health" },
  { char: "🚴", keywords: "cycling fitness exercise sport" },
  { char: "⛳", keywords: "golf sports activity" },
  // Health
  { char: "🩺", keywords: "health doctor medical clinic" },
  { char: "💊", keywords: "health pharmacy medicine prescription medical" },
  { char: "🏥", keywords: "health hospital medical clinic" },
  { char: "🦷", keywords: "health dental dentist medical" },
  { char: "👓", keywords: "health glasses vision optical" },
  { char: "🧴", keywords: "personal care lotion toiletries health" },
  // Money & bills
  { char: "💰", keywords: "money savings income bills finance" },
  { char: "💵", keywords: "money cash income bills" },
  { char: "💳", keywords: "card credit payment bills finance" },
  { char: "🏦", keywords: "bank finance money transfer" },
  { char: "🧾", keywords: "bills receipt invoice taxes finance" },
  { char: "📈", keywords: "investing stocks finance income growth" },
  { char: "🪙", keywords: "money coins savings finance crypto" },
  { char: "💸", keywords: "money spending expense bills" },
  { char: "🏷️", keywords: "tag label price misc default" },
  // Shopping & personal
  { char: "🛍️", keywords: "shopping retail mall purchases" },
  { char: "👕", keywords: "clothing shopping apparel shirt" },
  { char: "👗", keywords: "clothing shopping apparel dress" },
  { char: "👟", keywords: "shoes clothing shopping sneakers" },
  { char: "👜", keywords: "bag purse accessories shopping" },
  { char: "⌚", keywords: "watch accessories shopping" },
  { char: "💄", keywords: "beauty cosmetics personal care makeup" },
  { char: "💇", keywords: "haircut salon personal care beauty" },
  { char: "✂️", keywords: "haircut salon barber personal care" },
  { char: "💅", keywords: "nails salon personal care beauty" },
  // Entertainment & subscriptions
  { char: "🎬", keywords: "movies entertainment cinema film streaming" },
  { char: "🎵", keywords: "music streaming entertainment audio" },
  { char: "📺", keywords: "tv streaming entertainment cable" },
  { char: "🎮", keywords: "games gaming entertainment hobby" },
  { char: "🎟️", keywords: "tickets events entertainment concert" },
  { char: "🎤", keywords: "music concert entertainment events" },
  { char: "📚", keywords: "books reading education hobby" },
  { char: "🎨", keywords: "art hobby crafts creative" },
  { char: "🎸", keywords: "music hobby instrument entertainment" },
  { char: "🎲", keywords: "games hobby entertainment" },
  // Pets
  { char: "🐶", keywords: "pet dog animal vet" },
  { char: "🐱", keywords: "pet cat animal vet" },
  { char: "🐾", keywords: "pet animal vet paw" },
  { char: "🐟", keywords: "pet fish animal aquarium" },
  // Work & income
  { char: "💼", keywords: "work business job income office" },
  { char: "🏢", keywords: "work office business rent" },
  { char: "✉️", keywords: "mail postage shipping office" },
  { char: "📦", keywords: "shipping packages delivery shopping" },
  // Gifts & misc
  { char: "🎁", keywords: "gifts presents giving holidays" },
  { char: "🎉", keywords: "party celebration events fun" },
  { char: "🎂", keywords: "birthday party celebration cake" },
  { char: "❤️", keywords: "love donation charity giving favorite" },
  { char: "🤝", keywords: "donation charity giving" },
  { char: "⭐", keywords: "favorite star misc important" },
  { char: "🔔", keywords: "reminder subscription alert misc" },
  { char: "☂️", keywords: "insurance protection misc" },
  { char: "🌐", keywords: "internet online web misc" },
  { char: "🔒", keywords: "security insurance protection misc" },
  { char: "⛪", keywords: "church donation giving faith" },
  { char: "🧩", keywords: "misc other hobby" },
  { char: "📌", keywords: "misc pin other default" },
];
